name: "Tests"

on: [pull_request]
jobs:
  lint:
    name: Tests ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', 'nightly']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --ignore-platform-reqs --optimize-autoloader --no-plugins --no-scripts --prefer-dist
    
    - name: Start container
      # For local testing, also run this before retrying tests: docker rm --force $(docker ps -aq)
      run: docker compose up -d && sleep 15

    - name: Run tests
      run: docker compose exec tests vendor/bin/phpunit --configuration phpunit.xml